apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: hello-dev
spec:
  selector:
    matchLabels:
      app: hello-dev
  replicas: 2 # tells deployment to run 1 pods matching the template
  template: 
    metadata:
      labels:
        app: hello-dev
    spec:
      containers:
      - name: myapp-container
        image: 172.30.1.1:5000/hello-world/alpine-node 
        command: ['node', '-e']
        args: 
          - require('http').createServer((req, res) => { res.end('Hello World') }).listen(8080)
            
     
        
